import './globals.css';

import Footer from '@/components/footer/Footer';
import type { Metadata } from 'next';
import NavBar from '@/components/navbar/NavBar';
import { ReduxProvider } from '@/redux/provider';
import SideBar from '@/components/sidebar/SideBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ height: '100%' }}>
      <body style={{ background: '#F5F5F5', display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
        <NavBar />
        <div style={{ flex: '1' }}><ReduxProvider>{children}</ReduxProvider></div>
        <Footer />
      </body>
    </html>
  );
}
