import "./globals.css";

import CartProvider from "@/providers/cart.provider";
import { Metadata } from "next";
import NavBar from "@/components/navbar/NavBar";
import { Providers } from "@/providers/provider";
import ToastProvider from "@/providers/toast.provider";

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          background: "#FAFDFB",
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
        }}
      >
        <Providers>
          <ToastProvider>
            <CartProvider>
              <NavBar />
              <div style={{ flex: "1" }}>{children}</div>
            </CartProvider>
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
